/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class d_hl_filescann_FileScanner */

#ifndef _Included_d_hl_filescann_FileScanner
#define _Included_d_hl_filescann_FileScanner
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     d_hl_filescann_FileScanner
 * Method:    nativeInitScanner
 * Signature: ([Ljava/lang/String;IIZLd/hl/filescann/FileScanner/ScanCallback;)V
 */
JNIEXPORT void JNICALL Java_d_hl_filescann_FileScanner_nativeInitScanner
  (JNIEnv *, jobject, jobjectArray, jint, jint, jboolean);

/*
 * Class:     d_hl_filescann_FileScanner
 * Method:    nativeSetCallback
 * Signature: (Ld/hl/filescann/FileScanner/ScanCallback;)V
 */
JNIEXPORT void JNICALL Java_d_hl_filescann_FileScanner_nativeSetCallback
  (JNIEnv *, jobject, jobject);

/*
 * Class:     d_hl_filescann_FileScanner
 * Method:    nativeStartScan
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_d_hl_filescann_FileScanner_nativeStartScan
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     d_hl_filescann_FileScanner
 * Method:    nativeStopScan
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_d_hl_filescann_FileScanner_nativeStopScan
  (JNIEnv *, jobject);

/*
 * Class:     d_hl_filescann_FileScanner
 * Method:    nativeRrecycle
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_d_hl_filescann_FileScanner_nativeRrecycle
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
